[package]
name = "libft_rpv"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.64.0"

[dev-dependencies]
concat-idents = "1.1.4"
rusty-fork = "0.3.0"

[dependencies]
libc = "0.2.139"

[features]
bonus = []
verbose = []
fork = []
